[package]
name = "pathfinder-common"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }

[features]
full-serde = []
debug = ["tagged", "tagged-debug-derive"]

[dependencies]
anyhow = { workspace = true }
bitvec = { workspace = true }
fake = { workspace = true, features = ["derive"] }
metrics = { workspace = true }
num-bigint = { workspace = true }
num-traits = "0.2"
paste = { workspace = true }
pathfinder-crypto = { version = "0.15.3", path = "../crypto" }
primitive-types = { workspace = true, features = ["serde"] }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = [
    "arbitrary_precision",
    "raw_value",
] }
serde_with = { workspace = true }
sha3 = { workspace = true }

# These crates aren't published as they're meant for internal use only.
# The version is just to satisfy cargo publish requirements.
tagged = { version = "0.0.1", path = "../tagged", optional = true }
tagged-debug-derive = { version = "0.0.1", path = "../tagged-debug-derive", optional = true }

thiserror = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }

[build-dependencies]
vergen = { workspace = true, features = ["git", "gitcl"] }
